apiVersion: v1
kind: Service
metadata:
    name: file-converter
    namespace: sds
spec:
    selector:
        app: file-converter # must match your deployment labels
    type: NodePort
    ports:
        - protocol: TCP
          port: 7000
          targetPort: 7000
          nodePort: 30003
