apiVersion: v1
kind: Service
metadata:
  name: file-converter
spec:
  selector:
    app: file-converter # must match your deployment labels
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
