apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detection
  namespace: sds
  labels:
    app: face-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-detection
  template:
    metadata:
      labels:
        app: face-detection
    spec:
      containers:
        - name: face-detection
          image: ghcr.io/cp-rektmart/sds_final_project_k8s/face-detection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000

          livenessProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 2
            periodSeconds: 5
