apiVersion: v1
kind: Service
metadata:
  name: face-detection
  namespace: sds
spec:
  selector:
    app: bff # must match your deployment labels
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30002
