apiVersion: v1
kind: Service
metadata:
    name: bff
    namespace: sds
spec:
    selector:
        app: bff
    type: NodePort
    ports:
        - protocol: TCP
          port: 7000
          targetPort: 7000
          nodePort: 30001
